import type { BinderConfig, Repository, Scope } from '../config/types';
import { getDefaultRepoPath } from '../../utils/filesystem';

/**
 * Scope configuration for generating context map sections
 */
interface ScopeConfig {
  emoji: string;
  title: string;
  subtitle: string;
  permissions: string;
  instructions: string[];
}

const SCOPE_CONFIGS: Record<Scope, ScopeConfig> = {
  owner: {
    emoji: '🟢',
    title: 'OWNER',
    subtitle: 'Full Authority',
    permissions: 'Full read/write access',
    instructions: [
      'You are responsible for architecture, implementation, and refactoring.',
      'Make changes freely to improve code quality and functionality.',
      'You have complete authority over these repositories.',
    ],
  },
  platform: {
    emoji: '🟡',
    title: 'PLATFORM',
    subtitle: 'Restricted Contributor',
    permissions: 'Limited write access',
    instructions: [
      'Only make minimal changes when necessary to support OWNER scope.',
      'Strictly adhere to existing patterns and conventions.',
      'Do not refactor or restructure code.',
      'Changes should be small, focused, and well-justified.',
    ],
  },
  reference: {
    emoji: '🔴',
    title: 'REFERENCE',
    subtitle: 'Read Only',
    permissions: 'Read-only',
    instructions: [
      'Use for validation and historical context only.',
      'Do not suggest modifications to these repositories.',
      'Reference for understanding patterns and dependencies.',
    ],
  },
};

/**
 * Group repositories by their scope
 */
function groupByScope(repos: Repository[]): Record<Scope, Repository[]> {
  const groups: Record<Scope, Repository[]> = {
    owner: [],
    platform: [],
    reference: [],
  };

  for (const repo of repos) {
    groups[repo.scope].push(repo);
  }

  return groups;
}

/**
 * Get the display path for a repository
 */
function getDisplayPath(repo: Repository): string {
  return repo.path ?? getDefaultRepoPath(repo.name);
}

/**
 * Generate a scope section for the context map
 */
function generateScopeSection(scope: Scope, repos: Repository[]): string {
  if (repos.length === 0) {
    return '';
  }

  const config = SCOPE_CONFIGS[scope];
  const lines: string[] = [];

  lines.push(`## ${config.emoji} SCOPE: ${config.title} (${config.subtitle})`);
  lines.push('');
  lines.push('**Repositories:**');

  for (const repo of repos) {
    const displayPath = getDisplayPath(repo);
    lines.push(`- \`${repo.name}\` at \`${displayPath}\``);
    if (repo.notes) {
      lines.push(`  - *${repo.notes}*`);
    }
  }

  lines.push('');
  lines.push(`**Permissions:** ${config.permissions}`);
  lines.push('');
  lines.push('**Instructions:**');
  for (const instruction of config.instructions) {
    lines.push(`- ${instruction}`);
  }

  return lines.join('\n');
}

/**
 * Generate the CONTEXT_MAP.md content from a binder configuration
 */
export function generateContextMap(config: BinderConfig): string {
  const lines: string[] = [];
  const timestamp = new Date().toISOString();

  // Header
  lines.push('# WORKSPACE TOPOLOGY & SCOPE DEFINITIONS');
  lines.push('');
  lines.push(`**Workspace:** ${config.name}`);
  lines.push(`**Generated:** ${timestamp}`);
  lines.push('');
  lines.push(
    'You are operating in a multi-repository workspace. Use this map to understand your permissions and boundaries.'
  );
  lines.push('');
  lines.push('---');
  lines.push('');

  // Group repos by scope
  const grouped = groupByScope(config.repos);

  // Generate sections for each scope (in order: owner, platform, reference)
  const scopes: Scope[] = ['owner', 'platform', 'reference'];
  const sections: string[] = [];

  for (const scope of scopes) {
    const section = generateScopeSection(scope, grouped[scope]);
    if (section) {
      sections.push(section);
    }
  }

  lines.push(sections.join('\n\n---\n\n'));

  // Footer
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('*This file was auto-generated by Binder. Do not edit manually.*');

  return lines.join('\n');
}
